apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pexel-api
  template:
    metadata:
      labels:
        app: pexel-api
    spec:
      containers:
      - name: pexel-api
        image: nginx:alpine
        ports:
        - containerPort: 8080

